# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  name: $(buildPoolName) # Runs on OnPrem Windows (for now)
  demands:
    - Agent.Name -equals $(buildAgentName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: npm install
    displayName: 'npm install'

  - script: npm run build
    displayName: 'npm run build'

  - script: |
      npm pack
    displayName: 'Package for npm release'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '*.tgz'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy npm package'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: 'package.json'
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: 'Copy package.json'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: npm
    displayName: 'Publish npm artifact'
